### ISSUE TITLE
Support for Kings Lab Projects' iframes.

### ISSUE THREAD

**Issue by jasonjan2003** [badgerherald/badgerherald.com#113]
Expecting use of https://projects.knightlab.com/  tools next semester, we should make sure these iframes look as nice as possible on our article pages.

try in your dev
`<iframe src="http://cdn.knightlab.com/libs/storymapjs/latest/embed/?url=https://www.googledrive.com/host/0B4x3OWTtTHGyTjZhaVNmTXJVSDQ/published.json" frameborder="0" width="100%" height="800"></iframe>`

**Comment by wjhdev** [comment]
No plans to use these iframes today. Closing.
